<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>MRT路線進出站時間模擬器</AssemblyName>
    <RootNamespace>MrtRouteSimulator.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MrtRouteSimulator.Engine/MrtRouteSimulator.Engine.csproj" />
  </ItemGroup>
</Project>
