using System.Globalization;
using System.Windows;
using System.Windows.Data;
using MrtRouteSimulator.Engine;

namespace MrtRouteSimulator.App;

/// <summary>集中管理僅供 WPF 顯示的繁體中文名稱；不影響專案 JSON 或識別碼。</summary>
internal static class UiDisplayText
{
    private static readonly IReadOnlyDictionary<string, string> Headers = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["SchematicPosition"] = "示意水平位置", ["SchematicLane"] = "示意股道（上負下正）", ["PlatformNumber"] = "月台號碼",
        ["PlatformBodyId"] = "共用站體編號", ["DisplaySide"] = "站體位置",
        ["StopPositionReference"] = "停點基準",
        ["Id"] = "編號", ["Name"] = "名稱", ["Kind"] = "類型", ["Detail"] = "說明",
        ["From"] = "起點節點", ["To"] = "終點節點", ["LengthMeters"] = "長度（m）",
        ["Directionality"] = "通行方向", ["DefaultSpeedKmh"] = "預設速限（km/h）",
        ["FromPortSide"] = "起點接軌側（A/B）", ["ToPortSide"] = "終點接軌側（A/B）",
        ["BackingKind"] = "內部類型", ["DefaultDwellSeconds"] = "預設停站秒數", ["Platforms"] = "月台",
        ["Station"] = "車站", ["TrackEdge"] = "軌道區段", ["StartOffsetMeters"] = "起始偏移（m）",
        ["StopOffsetMeters"] = "停車偏移（m）", ["EndOffsetMeters"] = "終止偏移（m）",
        ["EffectiveLengthMeters"] = "有效長度（m）", ["Direction"] = "方向", ["PassengerService"] = "可載客",
        ["LimitKmh"] = "速限（km/h）", ["GradePermille"] = "坡度（‰）", ["IsAutoGenerated"] = "系統自動建立",
        ["Traversals"] = "通過路徑", ["Stops"] = "路線停靠站", ["CandidatePlatforms"] = "候選月台",
        ["Instructions"] = "停站指令", ["Stations"] = "車站", ["Action"] = "動作", ["DwellSeconds"] = "停站秒數",
        ["PassingSpeedKmh"] = "通過速限（km/h）", ["MaxSpeedKmh"] = "最高速度（km/h）",
        ["Acceleration"] = "加速度（m/s²）", ["ServiceBrake"] = "營運煞車減速度（m/s²）",
        ["EmergencyBrake"] = "緊急煞車減速度（m/s²）", ["Jerk"] = "加加速度（m/s³）",
        ["TractionDecay"] = "牽引衰減（每秒）", ["CoastingDeceleration"] = "惰行減速度（m/s²）",
        ["DefaultStopPattern"] = "預設停站模式", ["CompatibleServiceTypes"] = "相容服務類型",
        ["ColorHex"] = "顏色", ["RunPrefix"] = "車次前綴", ["DefaultVehicleType"] = "預設車型",
        ["Priority"] = "優先序", ["CanRequestOvertake"] = "可要求越行", ["PreferredPlatforms"] = "偏好月台",
        ["ServiceRoutes"] = "服務路徑", ["Run"] = "車次", ["Time"] = "時間", ["Service"] = "服務",
        ["Route"] = "路徑", ["Origin"] = "起始月台", ["Vehicle"] = "車輛",
        ["FirstDepartureSeconds"] = "首班發車秒數", ["HeadwaySeconds"] = "班距秒數", ["RunCount"] = "班次數",
        ["ServiceType"] = "服務類型", ["VehicleType"] = "車型", ["StopPattern"] = "停站模式",
        ["OriginPlatform"] = "起始月台", ["VehicleId"] = "車輛編號", ["ContinueAfterTerminal"] = "終點後續行",
        ["DepartureSeconds"] = "發車秒數", ["ServiceRunId"] = "車次編號", ["ContinuationServiceRunId"] = "接續車次編號",
        ["DistanceFromPreviousKm"] = "與前站距離（km）", ["ProjectName"] = "專案名稱", ["ProjectId"] = "專案編號"
    };

    public static string Header(string propertyName) => Headers.TryGetValue(propertyName, out var text) ? text : propertyName;

    public static string Enum(Enum value) => value switch
    {
        StopPositionReference.TrainFront => "車頭（相容）", StopPositionReference.TrainCenter => "車體中心",
        PlatformSide.Auto => "自動（內側）", PlatformSide.Above => "軌道上側", PlatformSide.Below => "軌道下側",
        TrainDirection.Outbound => "下行",
        TrainDirection.Inbound => "上行",
        TrackDirection.Both => "雙向",
        TrackDirection.Outbound => "下行",
        TrackDirection.Inbound => "上行",
        TrackNodeKind.Boundary => "邊界", TrackNodeKind.Ordinary => "一般節點", TrackNodeKind.Junction => "岔接點",
        TrackNodeKind.Switch => "道岔", TrackNodeKind.Crossing => "平交／交叉點", TrackNodeKind.BufferStop => "止衝擋",
        TrackNodeKind.DepotBoundary => "機廠邊界", TrackNodeKind.Other => "其他",
        TrackDirectionality.Bidirectional => "雙向", TrackDirectionality.ForwardOnly => "僅正向", TrackDirectionality.ReverseOnly => "僅反向",
        TrackEdgeKind.Mainline => "正線", TrackEdgeKind.PlatformTrack => "月台線", TrackEdgeKind.PassingTrack => "待避線",
        TrackEdgeKind.Siding => "側線", TrackEdgeKind.Crossover => "橫渡線", TrackEdgeKind.Turnback => "折返線",
        TrackEdgeKind.PocketTrack => "袋狀軌", TrackEdgeKind.TailTrack => "尾軌", TrackEdgeKind.DepotLead => "機廠引線",
        TrackEdgeKind.Approach => "進場線", TrackEdgeKind.Other => "其他",
        TraversalDirection.Forward => "正向", TraversalDirection.Reverse => "反向",
        ConflictResourceKind.Other => "其他", ConflictResourceKind.Switch => "道岔", ConflictResourceKind.Crossover => "橫渡線",
        ConflictResourceKind.Block => "閉塞區間", ConflictResourceKind.Platform => "月台", ConflictResourceKind.PocketTrack => "袋狀軌",
        ConflictResourceKind.TailTrack => "尾軌",
        TurnbackFacilityKind.TailTrack => "尾軌", TurnbackFacilityKind.PocketTrack => "袋狀軌",
        TurnbackFacilityKind.Crossover => "橫渡線", TurnbackFacilityKind.Siding => "側線", TurnbackFacilityKind.Other => "其他",
        StopPatternAction.Stop => "停站", StopPatternAction.Pass => "跨站", StopPatternAction.Turnback => "折返",
        OperationProfileMode.BasicPhysics => "基礎物理", OperationProfileMode.RealisticOperations => "寫實營運",
        SimulationEngineKind.V1BasicPhysics => "V1 基礎物理", SimulationEngineKind.V2RealisticOperations => "V2 寫實營運",
        MovingBlockMode.Independent => "獨立運行", MovingBlockMode.Monitoring => "監看", MovingBlockMode.Control => "控制",
        BrakingEstimationMode.Service => "營運煞車", BrakingEstimationMode.Emergency => "緊急煞車",
        ProjectValidationSeverity.Error => "錯誤", ProjectValidationSeverity.Warning => "警告", ProjectValidationSeverity.Info => "資訊",
        _ => value.ToString()
    };

    public static string FacilityKind(FacilityEditorKind kind) => kind switch
    {
        FacilityEditorKind.Turnback => "折返設施",
        FacilityEditorKind.Passing => "待避設施",
        FacilityEditorKind.CrossoverEdge => "橫渡線",
        _ => kind.ToString()
    };

    public static string ProjectValidation(ProjectValidationMessage message) =>
        $"{Enum(message.Severity)}　{ValidationMessage(message.Message)}";

    public static string ValidationMessage(string message) => message
        .Replace("Schema", "格式版本", StringComparison.Ordinal)
        .Replace("topology", "拓撲", StringComparison.OrdinalIgnoreCase)
        .Replace("ServiceRoute", "服務路徑", StringComparison.Ordinal)
        .Replace("service route", "服務路徑", StringComparison.OrdinalIgnoreCase)
        .Replace("TrackEdge", "軌道區段", StringComparison.Ordinal)
        .Replace("Track Edge", "軌道區段", StringComparison.Ordinal)
        .Replace("TrackNode", "軌道節點", StringComparison.Ordinal)
        .Replace("Track Node", "軌道節點", StringComparison.Ordinal)
        .Replace("traversal", "通過區段", StringComparison.OrdinalIgnoreCase)
        .Replace("edge-local", "區段內", StringComparison.OrdinalIgnoreCase)
        .Replace("virtual track", "虛擬軌道", StringComparison.OrdinalIgnoreCase)
        .Replace("runtime", "執行階段", StringComparison.OrdinalIgnoreCase)
        .Replace("legacy", "相容", StringComparison.OrdinalIgnoreCase);

    public static string Boolean(bool value) => value ? "是" : "否";

    public static bool TryParseBoolean(string text, out bool value)
    {
        if (text.Equals("是", StringComparison.OrdinalIgnoreCase) || bool.TryParse(text, out value) && value)
        {
            value = true;
            return true;
        }

        if (text.Equals("否", StringComparison.OrdinalIgnoreCase) || bool.TryParse(text, out value) && !value)
        {
            value = false;
            return true;
        }

        value = false;
        return false;
    }

    public static bool TryParseEnum(Type targetType, string text, out object? value)
    {
        foreach (var candidate in System.Enum.GetValues(targetType).Cast<Enum>())
        {
            if (string.Equals(text, Enum(candidate), StringComparison.OrdinalIgnoreCase)
                || string.Equals(text, candidate.ToString(), StringComparison.OrdinalIgnoreCase))
            {
                value = candidate;
                return true;
            }
        }

        value = null;
        return false;
    }
}

internal sealed class TraditionalChineseEnumConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        value is Enum enumValue ? UiDisplayText.Enum(enumValue) : value;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) =>
        value is string text && UiDisplayText.TryParseEnum(targetType, text.Trim(), out var parsed)
            ? parsed!
            : DependencyProperty.UnsetValue;
}
